spring:

  datasource:
    url: ENC(MBPB5/kMEvmdTIaWA5zMC3EBktd84imdo49CjN0OPT07nEdj8vPxFpsA/TxPn28XYdOPt11rcWuwXbmsXOHaW1Zxo4vG3JFH)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username : ENC(5HgYPv1SJGsfy5ARg5tA2w==)
    password: ENC(Z/dZCvHw+MzOoW/55rhVGUCRGaAZN55o)

  application :
    name : s-market

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  mail:
    host: smtp.naver.com
    port : 465
    username: ENC(tKQT3s7pfFzfHR8AmF/HTyiFeIPVzGsPf0suk4WSl0Y=)
    password: ENC(DThMo2MyRt1krXc/qQR8YfSq84w8+PGE)
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.enable : true
      mail.smtp.ssl.trust : smtp.naver.com

  data:
    redis:
      host: localhost
      port: 6379

server:
  address: localhost
  port: 8080

aes:
  secret-key : ENC(VbhFKKzW1SzNUNBg81/DjFo6IMM8VaXf8uOhIjIbx78=)

jwt:
  secret : ENC(0cTn4l6+af3hANu7Vot7s6qRwtFisx8pdCzuFsEYnzHdZ1liOvr0ZOJUGI4GFD5WZYos0CTA4Gp248CUVpRkiA==)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

songhee:
  upload:
    path: /Users/user/Desktop/files/

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access: DEBUG